language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:

script:
  - npm run build

after_script:
  - cd docs
  - git init
  - git config user.name "russellmars"
  - git config user.email "russellmars@sina.com"
  - git add .
  - git commit -m "update site"
  - git push --force --quiet "https://${account}:${password}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/russellmars/lifeplus.git
